<?php

/**
 * @file
 * Install, update and uninstall functions for the module.
 */

declare(strict_types=1);

use Drupal\Core\Database\Database;

/**
 * Implements hook_requirements().
 */
function gnikolovski_payment_log_requirements($phase): array {
  $requirements = [];

  if ($phase == 'runtime') {
    if (ini_get('session.cookie_samesite') === 'None') {
      $requirements['gnikolovski_payment_log_cookie_samesite'] = [
        'title' => t('Cookie samesite attribute'),
        'description' => t('The "cookie_samesite" attribute is set to "None", which is necessary for the payment redirection to work properly.'),
        'severity' => REQUIREMENT_OK,
      ];
    }
    else {
      $requirements['gnikolovski_payment_log_cookie_samesite'] = [
        'title' => t('Cookie samesite attribute'),
        'description' => t('The "cookie_samesite" attribute must be set to "None" for the payment redirection to work properly. Please update your "services.yml" file.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}

/**
 * Implements hook_schema().
 */
function gnikolovski_payment_log_schema(): array {
  $schema['gnikolovski_payment_log'] = [
    'description' => 'Stores payment gateway request and response logs.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Primary Key: Unique payment log ID.',
      ],
      'order_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'description' => 'The order ID for which payment was processed.',
      ],
      'session_id' => [
        'type' => 'varchar',
        'length' => 1024,
        'not null' => FALSE,
        'description' => 'The session ID for which payment was processed.',
      ],
      'gateway_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'description' => 'The name of the payment gateway used for processing.',
      ],
      'request_time' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'description' => 'The Unix timestamp when the request was sent to payment gateway.',
      ],
      'request_data' => [
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
        'description' => 'JSON data sent to payment gateway.',
      ],
      'response_time' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'description' => 'The Unix timestamp when the response was received from payment gateway.',
      ],
      'response_data' => [
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
        'description' => 'JSON data received from payment gateway.',
      ],
      'canceled' => [
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Indicates whether the payment was canceled.',
      ],
      'attempt_count' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => 0,
        'description' => 'The number of attempts made to get the payment status.',
      ],
    ],
    'primary key' => ['id'],
    'indexes' => [
      'order_id' => ['order_id'],
      'request_time' => ['request_time'],
      'response_time' => ['response_time'],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11001(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'attempt_count')) {
    $spec = [
      'type' => 'int',
      'unsigned' => TRUE,
      'not null' => FALSE,
      'default' => 0,
      'description' => 'The number of attempts made to get the payment status.',
    ];
    $schema->addField('gnikolovski_payment_log', 'attempt_count', $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11002(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'session_id')) {
    $spec = [
      'type' => 'varchar',
      'length' => 1024,
      'not null' => FALSE,
      'description' => 'The session ID for which payment was processed.',
    ];
    $schema->addField('gnikolovski_payment_log', 'session_id', $spec);
  }
}
