<?php

/**
 * @file
 * Install, update and uninstall functions for the module.
 */

declare(strict_types=1);

use Drupal\Core\Database\Database;

/**
 * Implements hook_schema().
 */
function gnikolovski_payment_log_schema(): array {
  $schema['gnikolovski_payment_log'] = [
    'description' => 'Stores payment gateway request and response logs.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Primary Key: Unique payment log ID.',
      ],
      'email' => [
        'type' => 'varchar',
        'length' => 1024,
        'not null' => FALSE,
        'description' => 'The email address of the user who made the payment.',
      ],
      'order_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'description' => 'The order ID for which payment was processed.',
      ],
      'additional_data' => [
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
        'description' => 'Additional json data for the payment.',
      ],
      'gateway_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'description' => 'The name of the payment gateway used for processing.',
      ],
      'request_time' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'description' => 'The Unix timestamp when the request was sent to payment gateway.',
      ],
      'request_data' => [
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
        'description' => 'JSON data sent to payment gateway.',
      ],
      'response_time' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'description' => 'The Unix timestamp when the response was received from payment gateway.',
      ],
      'response_data' => [
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
        'description' => 'JSON data received from payment gateway.',
      ],
      'canceled' => [
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Indicates whether the payment was canceled.',
      ],
      'attempt_count' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => 0,
        'description' => 'The number of attempts made to get the payment status.',
      ],
    ],
    'primary key' => ['id'],
    'indexes' => [
      'order_id' => ['order_id'],
      'request_time' => ['request_time'],
      'response_time' => ['response_time'],
      'canceled' => ['canceled'],
      'attempt_count' => ['attempt_count'],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11001(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'attempt_count')) {
    $spec = [
      'type' => 'int',
      'unsigned' => TRUE,
      'not null' => FALSE,
      'default' => 0,
      'description' => 'The number of attempts made to get the payment status.',
    ];
    $schema->addField('gnikolovski_payment_log', 'attempt_count', $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11002(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'session_id')) {
    $spec = [
      'type' => 'varchar',
      'length' => 1024,
      'not null' => FALSE,
      'description' => 'The session ID for which payment was processed.',
    ];
    $schema->addField('gnikolovski_payment_log', 'session_id', $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11003(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'email')) {
    $spec = [
      'type' => 'varchar',
      'length' => 1024,
      'not null' => FALSE,
      'description' => 'The email address of the user who made the payment.',
    ];
    $schema->addField('gnikolovski_payment_log', 'email', $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11004(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'remote_order_id')) {
    $spec = [
      'type' => 'varchar',
      'length' => 255,
      'not null' => FALSE,
      'description' => 'The remote order ID for which payment was processed.',
    ];
    $schema->addField('gnikolovski_payment_log', 'remote_order_id', $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11005(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'remote_session_id')) {
    $spec = [
      'type' => 'varchar',
      'length' => 1024,
      'not null' => FALSE,
      'description' => 'The remote session ID for which payment was processed.',
    ];
    $schema->addField('gnikolovski_payment_log', 'remote_session_id', $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11006(): void {
  $schema = Database::getConnection()->schema();
  if ($schema->fieldExists('gnikolovski_payment_log', 'session_id')) {
    $schema->dropField('gnikolovski_payment_log', 'session_id');
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11007(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->indexExists('gnikolovski_payment_log', 'canceled')) {
    $spec = [
      'fields' => [
        'canceled' => [
          'type' => 'int',
          'size' => 'tiny',
          'not null' => TRUE,
          'default' => 0,
          'description' => 'Indicates whether the payment was canceled.',
        ],
      ],
    ];
    $schema->addIndex('gnikolovski_payment_log', 'canceled', ['canceled'], $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11008(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->indexExists('gnikolovski_payment_log', 'attempt_count')) {
    $spec = [
      'fields' => [
        'attempt_count' => [
          'type' => 'int',
          'unsigned' => TRUE,
          'not null' => FALSE,
          'default' => 0,
          'description' => 'The number of attempts made to get the payment status.',
        ],
      ],
    ];
    $schema->addIndex('gnikolovski_payment_log', 'attempt_count', ['attempt_count'], $spec);
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11009(): void {
  $schema = Database::getConnection()->schema();
  if ($schema->fieldExists('gnikolovski_payment_log', 'remote_order_id')) {
    $schema->dropField('gnikolovski_payment_log', 'remote_order_id');
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11010(): void {
  $schema = Database::getConnection()->schema();
  if ($schema->fieldExists('gnikolovski_payment_log', 'remote_session_id')) {
    $schema->dropField('gnikolovski_payment_log', 'remote_session_id');
  }
}

/**
 * Implements hook_update_N().
 */
function gnikolovski_payment_log_update_11011(): void {
  $schema = Database::getConnection()->schema();
  if (!$schema->fieldExists('gnikolovski_payment_log', 'additional_data')) {
    $spec = [
      'type' => 'text',
      'size' => 'big',
      'not null' => FALSE,
      'description' => 'Additional json data for the payment.',
    ];
    $schema->addField('gnikolovski_payment_log', 'additional_data', $spec);
  }
}
